In [3]:
import pandas as pd 
import numpy as np
import os

In [21]:
df=pd.read_excel(r'C:\Users\Haier\Desktop\COVID_FINAL_DATA.xlsx',0)
df.isnull().sum()
df=df.fillna(0)
df['Home Quarantine']=df['Home Quarantine'].apply(np.int64)
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace=True)
df

,Cumulative,Cumulative Test positive,Cumulative tests performed,Date,Discharged,Expired,Home Quarantine,New (last 24 hrs),Region,Still admitted,Tests performed in last 24 hours
0,48,2,80,2020-03-11 00:00:00,0,0,0,3,ICT,2,8
1,61,0,95,2020-03-11 00:00:00,0,0,0,6,Punjab,0,7
2,84,14,171,2020-03-11 00:00:00,1,0,0,1,Sindh,13,55
3,20,0,28,2020-03-11 00:00:00,0,0,0,0,KP,0,2
4,3,0,0,2020-03-11 00:00:00,0,0,0,0,KPTD,0,0
...,...,...,...,...,...,...,...,...,...,...,...
449,6224,475,5748,2020-05-13 00:00:00,127,4,127,11,GB,13,129
450,21257,759,21257,2020-05-13 00:00:00,632,6,632,1056,ICT,29,1056
451,31568,5021,32577,2020-05-13 00:00:00,2860,267,2860,971,KP,589,971
452,114762,13225,140212,2020-05-13 00:00:00,2780,214,2780,7159,Punjab,5700,5098
453,99117,12610,99117,2020-05-13 00:00:00,8668,218,8668,4064,Sindh,1495,4064

In [22]:
df.to_excel(r'C:\Users\Haier\Desktop\TimeSeries_KeyIndicators.xlsx',index=False)

In [28]:
df=pd.read_excel(r'C:\Users\Haier\Desktop\COVID_FINAL_DATA.xlsx',1)
df.isnull().sum()
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace=True)
df

,Date,Province Old,Suspected Cases Last Date,Suspected Cases Last 24 Hrs,Suspected Cases Cumulative,Lab Tests Last 24 Hrs,Lab Tests Cumulative,Confirmed Cases Last Date,Confirmed Cases Last 24 Hrs,Confirmed Cases Cumulative,...,Confirmed HW - Active Doctors,Confirmed HW - Active Nurses,Confirmed HW - Active Others,Confirmed HW - Active Total,Confirmed HW - Active Isolation,Confirmed HW - Active Hospital,Confirmed HW - Active Hospital Stable,Confirmed HW - Active Hospital Ventilator,Confirmed HW - Active Recovered,Confirmed HW - Active Deaths
0,2020-04-04,AJK,322,21,343,21,343,9,2,11,...,0.00,0,0,0,0,0,0,0,0,0
1,2020-04-04,Balochistan,2171,230,2401,0,2401,169,6,175,...,0.00,0,0,0,0,0,0,0,0,0
2,2020-04-04,GB,961,2,963,844,860,190,3,193,...,0.00,0,0,0,0,0,0,0,0,0
3,2020-04-04,ICT,2395,174,2569,174,2569,68,7,75,...,0.00,0,0,0,0,0,0,0,0,0
4,2020-04-04,KP,1938,431,2369,181,1624,311,32,343,...,0.00,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,2020-05-13,GB,6213,11,6224,129,5748,457,18,475,...,0.08,3,2,21,26,0,7,7,0,17
234,2020-05-13,ICT,20201,1056,21257,1056,21257,716,43,759,...,0.01,49,29,21,99,89,2,2,0,7
235,2020-05-13,KP,30597,971,31568,971,32577,4875,146,5021,...,0.15,117,46,101,264,168,37,36,1,57
236,2020-05-13,Punjab,107603,7159,114762,5098,140212,11869,1356,13225,...,0.20,85,46,53,184,23,89,89,0,72
237,2020-05-13,Sindh,95053,4064,99117,4064,99117,12017,593,12610,...,0.18,127,19,43,189,144,10,7,3,30

In [29]:
df.to_excel(r'C:\Users\Haier\Desktop\TimeSeries_KeyIndicators_Details.xlsx',index=False)

In [41]:
df=pd.read_excel(r'C:\Users\Haier\Desktop\COVID_FINAL_DATA.xlsx',2)
df.isnull().values.any()
df.to_excel(r'C:\Users\Haier\Desktop\TimeSeries_Action_Screen.xlsx',index=False)

In [43]:
df=pd.read_excel(r'C:\Users\Haier\Desktop\COVID_FINAL_DATA.xlsx',3)
df.isnull().values.any()
df.to_excel(r'C:\Users\Haier\Desktop\TimeSeries_Action_Call.xlsx',index=False)

In [44]:
df=pd.read_excel(r'C:\Users\Haier\Desktop\COVID_FINAL_DATA.xlsx',4)
df.isnull().sum()
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace=True)
df.to_excel(r'C:\Users\Haier\Desktop\TimeSeries_COVID_News.xlsx',index=False)

In [47]:
df=pd.read_excel(r'C:\Users\Haier\Desktop\COVID_FINAL_DATA.xlsx',5)
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace=True)
df.to_excel(r'C:\Users\Haier\Desktop\TimeSeries_NIH_Response.xlsx',index=False)

In [50]:
df=pd.read_excel(r'C:\Users\Haier\Desktop\COVID_FINAL_DATA.xlsx',6)
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace=True)
df.to_excel(r'C:\Users\Haier\Desktop\TimeSeries_NIH_Risk.xlsx',index=False)

In [53]:
df=pd.read_excel(r'C:\Users\Haier\Desktop\COVID_FINAL_DATA.xlsx',7)
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace=True)
df.to_excel(r'C:\Users\Haier\Desktop\TimeSeries_Province_Response.xlsx',index=False)

In [56]:
df=pd.read_excel(r'C:\Users\Haier\Desktop\COVID_FINAL_DATA.xlsx',8)
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace=True)
df.to_excel(r'C:\Users\Haier\Desktop\TimeSeries_Helpline_Calls.xlsx',index=False)

In [59]:
df=pd.read_excel(r'C:\Users\Haier\Desktop\COVID_FINAL_DATA.xlsx',9)
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace=True)
df.to_excel(r'C:\Users\Haier\Desktop\TimeSeries_Quarantine_Details.xlsx',index=False)

In [60]:
exit()